/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Blogs = {
  _id: string;
  _type: "blogs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featuredBlog?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  };
  blogs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: "job-search-coaching" | "career-coaching" | "executive-coaching";
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  author?: string;
  publishDate?: string;
  readDuration?: number;
  relatedBlogs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
};

export type Resources = {
  _id: string;
  _type: "resources";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  blogs?: {
    featuredBlog?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "blog";
    };
    blogs?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "blog";
    }>;
    _type: "blogs";
  };
};

export type Workshops = {
  _id: string;
  _type: "workshops";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  linkedinEngine?: Workshop;
};

export type Workshop = {
  _type: "workshop";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Cta;
  testimonials?: Testimonials;
  features?: Features;
  phases?: Phases;
  faqs?: Faqs;
  pricingPlans?: PricingPlans;
};

export type Services = {
  _id: string;
  _type: "services";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  resumeWriting?: Service;
};

export type Service = {
  _type: "service";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Cta;
};

export type CoachingProgram = {
  _id: string;
  _type: "coachingProgram";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?:
    | "job-search-coaching"
    | "career-search-coaching"
    | "executive-coaching";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Cta;
  firstParagraph?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  phases?: Phases;
  careerCoach?: CareerCoach;
  guarantees?: Guarantees;
  pricingPlans?: PricingPlans;
  faqs?: Faqs;
  secondParagraph?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  clients?: Clients;
  testimonials?: Testimonials;
  programs?: Programs;
  features?: Features;
  ctaSection?: CtaSection;
  faqs?: Faqs;
};

export type CtaSection = {
  _type: "ctaSection";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Cta;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
};

export type Programs = {
  _type: "programs";
  title?: string;
  programs?: Array<
    {
      _key: string;
    } & Program
  >;
};

export type Clients = {
  _type: "clients";
  title?: string;
  logos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Cta;
  desktopImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
  tabletImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
  mobileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
};

export type CustomPortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Features = {
  _type: "features";
  features?: Array<
    {
      _key: string;
    } & Feature
  >;
};

export type Testimonials = {
  _type: "testimonials";
  title?: string;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type CareerCoach = {
  _type: "careerCoach";
  title?: string;
  coachTitle?: string;
  coachImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
  coachStory?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type PricingPlans = {
  _type: "pricingPlans";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  pricingPlans?: Array<
    {
      _key: string;
    } & PricingPlan
  >;
  footnote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Guarantees = {
  _type: "guarantees";
  title?: string;
  guarantees?: Array<
    {
      _key: string;
    } & Guarantee
  >;
  footnote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Phases = {
  _type: "phases";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  phases?: Array<
    {
      _key: string;
    } & Phase
  >;
  footnote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Faqs = {
  _type: "faqs";
  title?: string;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
};

export type PricingPlan = {
  _type: "pricingPlan";
  tag?: "best-value" | "most-popular" | "most-flexible";
  title?: string;
  price?: number;
  benefits?: Array<string>;
};

export type Guarantee = {
  _type: "guarantee";
  title?: string;
  description?: CustomPortableText;
};

export type Phase = {
  _type: "phase";
  title?: string;
  description?: CustomPortableText;
  outcomes?: Array<string>;
};

export type Faq = {
  _type: "faq";
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Feature = {
  _type: "feature";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  benefits?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
  direction?: "left-to-right" | "right-to-left";
  cta?: Cta;
};

export type Program = {
  _type: "program";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
  cta?: Cta;
};

export type Testimonial = {
  _type: "testimonial";
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  name?: string;
  position?: string;
  organization?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "customImage";
  };
};

export type CustomImage = {
  _type: "customImage";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Cta = {
  _type: "cta";
  label?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Slug
  | Blogs
  | Blog
  | Resources
  | Workshops
  | Workshop
  | Services
  | Service
  | CoachingProgram
  | Home
  | CtaSection
  | Programs
  | Clients
  | Hero
  | CustomPortableText
  | Features
  | Testimonials
  | CareerCoach
  | PricingPlans
  | Guarantees
  | Phases
  | Faqs
  | PricingPlan
  | Guarantee
  | Phase
  | Faq
  | Feature
  | Program
  | Testimonial
  | CustomImage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Cta;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: HERO_QUERY
// Query: *[_type == "home"][0]{  hero {    title,    description,    cta,     "desktopImage": {        "url": desktopImage.asset->url,        "alt": desktopImage.alt    },     "tabletImage": {        "url": tabletImage.asset->url,        "alt": tabletImage.alt    } ,     "mobileImage": {        "url": mobileImage.asset->url,        "alt": mobileImage.alt    }    },}
export type HERO_QUERYResult = {
  hero: {
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: Cta | null;
    desktopImage: {
      url: string | null;
      alt: string | null;
    };
    tabletImage: {
      url: string | null;
      alt: string | null;
    };
    mobileImage: {
      url: string | null;
      alt: string | null;
    };
  } | null;
} | null;
// Variable: CLIENTS_QUERY
// Query: *[_type == "home"][0] {  clients {    title,    logos[] {      "url": asset->url,      "alt": alt    }  }}
export type CLIENTS_QUERYResult = {
  clients: {
    title: string | null;
    logos: Array<{
      url: string | null;
      alt: string | null;
    }> | null;
  } | null;
} | null;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "home"][0] {    testimonials {      title,      testimonials[] {        description,        name,        position,        organization,        "image": {          "url": image.asset->url,          "alt": image.alt        }      }    }  }
export type TESTIMONIALS_QUERYResult = {
  testimonials: {
    title: string | null;
    testimonials: Array<{
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      name: string | null;
      position: string | null;
      organization: string | null;
      image: {
        url: string | null;
        alt: string | null;
      };
    }> | null;
  } | null;
} | null;
// Variable: PROGRAMS_QUERY
// Query: *[_type == "home"][0] {programs {title,programs[] {title,description,cta,"image": {"url": image.asset->url,"alt":image.alt}}}}
export type PROGRAMS_QUERYResult = {
  programs: {
    title: string | null;
    programs: Array<{
      title: string | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      cta: Cta | null;
      image: {
        url: string | null;
        alt: string | null;
      };
    }> | null;
  } | null;
} | null;
// Variable: FEATURES_QUERY
// Query: *[_type == "home"][0] {features {features[] {title,description,benefits[],cta,direction,"image": {"url": image.asset->url,"alt":image.alt}}}}
export type FEATURES_QUERYResult = {
  features: {
    features: Array<{
      title: string | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      benefits: Array<string> | null;
      cta: Cta | null;
      direction: "left-to-right" | "right-to-left" | null;
      image: {
        url: string | null;
        alt: string | null;
      };
    }> | null;
  } | null;
} | null;
// Variable: CTA_SECTION_QUERY
// Query: *[_type == "home"][0]{ctaSection {title,description,cta,"image": {"url":image.asset->url,"alt":image.alt}}}
export type CTA_SECTION_QUERYResult = {
  ctaSection: {
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: Cta | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  } | null;
} | null;
// Variable: FAQS_QUERY
// Query: *[_type == "home"][0] {faqs {title,faqs[] {question,answer}}}
export type FAQS_QUERYResult = {
  faqs: {
    title: string | null;
    faqs: Array<{
      question: string | null;
      answer: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }> | null;
  } | null;
} | null;
// Variable: JOB_SEARCH_QUERY
// Query: *[_type == "coachingProgram" && category == "job-search-coaching"][0] {  title,  description,  cta,  firstParagraph,  phases,  "careerCoach": {    "title": careerCoach.title,    "coachTitle": careerCoach.coachTitle,    "coachImage": {      "url": careerCoach.coachImage.asset->url,      "alt": careerCoach.coachImage.alt    },    "coachStory": careerCoach.coachStory  },  guarantees,  pricingPlans,  faqs,  secondParagraph}
export type JOB_SEARCH_QUERYResult = {
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  cta: Cta | null;
  firstParagraph: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  phases: Phases | null;
  careerCoach: {
    title: string | null;
    coachTitle: string | null;
    coachImage: {
      url: string | null;
      alt: string | null;
    };
    coachStory: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  };
  guarantees: Guarantees | null;
  pricingPlans: PricingPlans | null;
  faqs: Faqs | null;
  secondParagraph: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "home"][0]{\n  hero {\n    title,\n    description,\n    cta,\n     "desktopImage": {\n        "url": desktopImage.asset->url,\n        "alt": desktopImage.alt\n    },\n     "tabletImage": {\n        "url": tabletImage.asset->url,\n        "alt": tabletImage.alt\n    } ,\n     "mobileImage": {\n        "url": mobileImage.asset->url,\n        "alt": mobileImage.alt\n    }  \n  },\n}\n': HERO_QUERYResult;
    '\n*[_type == "home"][0] {\n  clients {\n    title,\n    logos[] {\n      "url": asset->url,\n      "alt": alt\n    }\n  }\n}\n': CLIENTS_QUERYResult;
    '\n  *[_type == "home"][0] {\n    testimonials {\n      title,\n      testimonials[] {\n        description,\n        name,\n        position,\n        organization,\n        "image": {\n          "url": image.asset->url,\n          "alt": image.alt\n        }\n      }\n    }\n  }\n': TESTIMONIALS_QUERYResult;
    '\n*[_type == "home"][0] {\nprograms {\ntitle,\nprograms[] {\ntitle,\ndescription,\ncta,\n"image": {\n"url": image.asset->url,\n"alt":image.alt\n}\n}\n}\n}\n': PROGRAMS_QUERYResult;
    '\n*[_type == "home"][0] {\nfeatures {\nfeatures[] {\ntitle,\ndescription,\nbenefits[],\ncta,\ndirection,\n"image": {\n"url": image.asset->url,\n"alt":image.alt\n}\n}\n}\n}\n': FEATURES_QUERYResult;
    '\n*[_type == "home"][0]{\nctaSection {\n\ntitle,\ndescription,\ncta,\n"image": {\n"url":image.asset->url,\n"alt":image.alt\n}\n}\n}\n': CTA_SECTION_QUERYResult;
    '\n*[_type == "home"][0] {\nfaqs {\ntitle,\nfaqs[] {\nquestion,\nanswer\n}\n}\n}\n': FAQS_QUERYResult;
    '\n*[_type == "coachingProgram" && category == "job-search-coaching"][0] {\n  title,\n  description,\n  cta,\n  firstParagraph,\n  phases,\n  "careerCoach": {\n    "title": careerCoach.title,\n    "coachTitle": careerCoach.coachTitle,\n    "coachImage": {\n      "url": careerCoach.coachImage.asset->url,\n      "alt": careerCoach.coachImage.alt\n    },\n    "coachStory": careerCoach.coachStory\n  },\n  guarantees,\n  pricingPlans,\n  faqs,\n  secondParagraph\n}\n': JOB_SEARCH_QUERYResult;
  }
}
